### ISSUE TITLE
openapi_rspec converts the parameters to strings

### ISSUE THREAD

**Issue by harashoo** [skryukov/openapi_rspec#11]
openapi_rspec converts the parameters to strings.

This is why the parameters of the test are different from the actual parameters.

example:
```
# users_controller
def create
  binding.pry
  User.create(user_params)
end
```

```
# parameters of openapi_rspec
[1] pry(#<UsersController>)> request.body.read
=> "user[admin]=false"

# the actual parameters
[1] pry(#<UsersController>)> request.body.read
=> "{\"user\":{\"admin\":false}}"
```

**Comment by skryukov** [comment]
Hi @harashoo!

Yep, the issue is - openapi_rspec sends everything as a query params by default (this is a pretty ugly bug if you ask me =)). See #9 as a (temporary?) solution. I'll release an update with these changes in a couple of days. Cheers!

**Comment by harashoo** [comment]
Thanks!
