### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by ThomasKoppensteiner** [skryukov/openapi_rspec#12]
Can you please release the current master or a version, which includes #9, on [rubygems.org](https://rubygems.org/gems/openapi_rspec)?

**Comment by skryukov** [comment]
Hi, @ThomasKoppensteiner! Thanks for the issue-reminder. =)

The problem is - I don't work at medsolutions for half a year for now and, as a result, don't have permissions to the repo. We are working on this problem, so I'll do my best to release gem in a couple of days. Cheers!

**Comment by skryukov** [comment]
Finally released a 0.5 version, sorry for the waiting.
